### ISSUE TITLE
homeassistant

### ISSUE THREAD

**Issue by iot-root** [iot-root/gardyn-of-eden#2]
Add Home Assistant compatibility

**Comment by iot-root** [comment]
dashboard yaml
```
title: Home
views:
  - title: Gardyn
    path: gardyn
    icon: mdi:flower-tulip-outline
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - graph: line
            type: sensor
            entity: sensor.gardyn_temperature
            detail: 1
          - type: sensor
            entity: sensor.gardyn_humidity
            graph: line
          - type: gauge
            entity: sensor.gardyn_water_level
            name: 'Water Level '
            unit: cm
            severity:
              green: 6
              yellow: 9
              red: 11
            min: 6
            max: 12
            needle: true
      - type: light
        entity: light.gardyn_light
      - type: light
        entity: light.gardyn_pump
        icon: mdi:water-pump
      - type: entities
        entities:
          - entity: sensor.gardyn_humidity
            name: Humidity
          - entity: sensor.gardyn_pcb_temperature
            name: PCB Temperature
          - entity: sensor.gardyn_temperature
            name: Temperature
          - entity: sensor.gardyn_water_level
            name: Water Level
        title: gardyn
      - chart_type: line
        period: hour
        type: statistics-graph
        entities:
          - sensor.gardyn_temperature
        stat_types:
          - mean
          - min
          - max
      - chart_type: line
        period: hour
        type: statistics-graph
        entities:
          - sensor.gardyn_water_level
        stat_types:
          - mean
          - min
          - max
      - chart_type: line
        period: hour
        type: statistics-graph
        entities:
          - sensor.gardyn_humidity
        stat_types:
          - mean
          - min
          - max
      - chart_type: line
        period: hour
        type: statistics-graph
        entities:
          - sensor.gardyn_pcb_temperature
        stat_types:
          - mean
          - min
          - max
   ```
